# Generated by Django 6.0.3 on 2026-03-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserequest',
            name='first_approver_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='first_approver_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='second_approver_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='second_approver_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='treasurer_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='treasurer_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
