# Generated by Django 6.0.3 on 2026-04-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_expenserequest_is_paid_expenserequest_paid_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserequest',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer'), ('mpesa', 'M-Pesa')], max_length=50),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
