# Generated by Django 6.0.3 on 2026-04-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_expenserequest_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenserequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('first_approved', 'First Approved'), ('second_approved', 'Second Approved'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Not Approved')], default='draft', max_length=20),
        ),
    ]
