# Generated by Django 6.0.3 on 2026-04-09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_expenserequest_payment_status'),
        ('expenses', '0007_alter_expenserequest_status'),
    ]

    operations = []
