# Generated by Django 6.0.3 on 2026-04-09 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_merge_expenserequest_payment_branches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenserequest',
            name='payment_status',
        ),
    ]
