# Generated by Django 6.0.3 on 2026-04-21 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_notification_notification_type'),
        ('expenses', '0009_remove_expenserequest_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserequest',
            name='budget_choice',
            field=models.CharField(blank=True, choices=[('church_budget', 'Church Budget'), ('contribution1', 'Contribution 1'), ('contribution2', 'Contribution 2'), ('mk', 'MK')], max_length=20),
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('contribution1_name', models.CharField(blank=True, max_length=100)),
                ('contribution1_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('contribution2_name', models.CharField(blank=True, max_length=100)),
                ('contribution2_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
            ],
            options={
                'unique_together': {('department',)},
            },
        ),
    ]
