# Generated by Django 6.0.3 on 2026-04-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0007_alter_retirementform_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retirementform',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('first_approved', 'First Approved'), ('second_approved', 'Second Approved'), ('approved', 'Closed'), ('paid', 'Paid'), ('rejected', 'Not Approved'), ('rejected_for_editing', 'Rejected for Editing'), ('open', 'Open')], default='draft', max_length=20),
        ),
    ]
