# Generated by Django 6.0.3 on 2026-04-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0008_alter_retirementform_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='retirementform',
            name='exp_request_form_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
