# Generated by Django 6.0.3 on 2026-04-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0009_retirementform_exp_request_form_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retirementform',
            name='exp_request_form_no',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
