# Generated by Django 6.0.3 on 2026-04-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('pending_expense', 'Pending Expense'), ('pending_retirement', 'Pending Retirement'), ('approved_expense', 'Approved Expense'), ('approved_retirement', 'Approved Retirement'), ('rejected_expense', 'Rejected Expense'), ('rejected_retirement', 'Rejected Retirement'), ('general', 'General')], default='general', max_length=30),
        ),
    ]
