# Generated by Django 6.0.3 on 2026-04-06 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification_read_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationcode',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department'),
        ),
    ]
