# Generated by Django 6.0.3 on 2026-04-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_registrationcode_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('pending_expense', 'Pending Expense'), ('pending_retirement', 'Pending Retirement'), ('approved_expense', 'Approved Expense'), ('approved_retirement', 'Approved Retirement'), ('rejected_expense', 'Rejected Expense'), ('rejected_retirement', 'Rejected Retirement'), ('paid_expense', 'Paid Expense'), ('paid_retirement', 'Paid Retirement'), ('general', 'General')], default='general', max_length=30),
        ),
    ]
